module.exports = {
    EMPTY_ROOM_GRACE_MS: Number(process.env.EMPTY_ROOM_GRACE_MS) || 120_000,
    MAX_CODE_BYTES: 500 * 1024,
    EXECUTE_MAX_TIMEOUT_MS: Number(process.env.EXECUTE_TIMEOUT_MS) || 8000,
    MAX_AI_REQUESTS_PER_HOUR: Number(process.env.MAX_AI_REQUESTS_PER_HOUR) || 10,
    GITHUB_MAX_FILE_BYTES: Number(process.env.GITHUB_IMPORT_MAX_FILE_BYTES) || 2 * 1024 * 1024,
    GITHUB_MAX_FILE_COUNT: Number(process.env.GITHUB_IMPORT_MAX_FILES) || 5000,
    ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY || '1h',
    REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY || '7d',
    RESET_TOKEN_EXPIRY_MS: Number(process.env.RESET_TOKEN_EXPIRY_MS) || 3600000,
};